### PR TITLE
upgrade to ZIO 2.0.0-M4

### PR DESCRIPTION
**Pull request by yisraelU**
Please let me know if there is anything missing, or anything else I can do
It compiles and tests run successfully

### CODE REVIEW

**Comment by yisraelU** [comment]
I meant to write 2.0.0-M4 not 2.0.4 :)

**Comment by svroonland** [comment]
Thanks for the contribution @yisraelU, looks good. The 2.12 builds seem to be failing, so if you could have a look at those.

I think it's best to wait until a bit closer to ZIO 2.0 release (the 1.0 RC phase took quite some time) before merging to master. If it's useful for you, we could modify the build to publish snapshots of zio-amqp for ZIO 2.0.

**Comment by yisraelU** [comment]
@svroonland 
Thanks for looking at the PR so quickly.
The issue with Scala 2.12 is it doesn't like inferring to Type Any for the R parameter of the ZIO effect in the withChannel method
I can add type ascriptions explicitly to make the error go away.
Do you have a better solution?
Also i noticed the only lambda ever passed in is a Channel => Task[A] perhaps withChannel should fix the ZIO R param to Any

**Comment by svroonland** [comment]
@yisraelU `Channel => Task[A]` is probably sufficient, let's try that

**Comment by svroonland** [comment]
Thanks!

**Comment by svroonland** [comment]
Woops, I didn't intend to merge. But ah well, not much harm for now.

**Pull request merged**
